"""Lockfile management for reproducible skill installs.

The lockfile (agr.lock) pins exact git commit SHAs for every resolved
dependency so that ``agr sync`` produces identical results across
machines and over time.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import ClassVar

import tomlkit
import tomlkit.items
from tomlkit import TOMLDocument
from tomlkit.exceptions import TOMLKitError

from agr.config import DEPENDENCY_TYPE_RALPH, Dependency
from agr.exceptions import ConfigError

LOCKFILE_FILENAME = "agr.lock"
LOCKFILE_VERSION = 1


@dataclass
class LockedSkill:
    """A single locked dependency entry.

    Remote skills have handle/source/commit/content_hash.
    Local skills have path only (resolved from disk at sync time).
    Both have installed_name.
    """

    installed_name: str
    # Remote fields
    handle: str | None = None
    source: str | None = None
    commit: str | None = None
    content_hash: str | None = None
    # Local field
    path: str | None = None

    # Mapping from dataclass field names to TOML key names.
    # Order defines the serialization order in the lockfile.
    _TOML_OPTIONAL_FIELDS: ClassVar[tuple[tuple[str, str], ...]] = (
        ("handle", "handle"),
        ("path", "path"),
        ("source", "source"),
        ("commit", "commit"),
        ("content_hash", "content-hash"),
    )

    @property
    def is_local(self) -> bool:
        return self.path is not None

    @property
    def identifier(self) -> str:
        """Unique identifier matching Dependency.identifier."""
        return self.path or self.handle or ""

    @classmethod
    def from_dict(cls, data: dict[str, object]) -> LockedSkill:
        """Deserialize a TOML table into a LockedSkill."""

        def _get_optional_str(key: str) -> str | None:
            value = data.get(key)
            return str(value) if value is not None else None

        return cls(
            installed_name=str(data.get("installed-name", "")),
            handle=_get_optional_str("handle"),
            path=_get_optional_str("path"),
            source=_get_optional_str("source"),
            commit=_get_optional_str("commit"),
            content_hash=_get_optional_str("content-hash"),
        )

    def to_toml_table(self) -> tomlkit.items.Table:
        """Serialize this entry into a tomlkit Table."""
        table = tomlkit.table()
        for attr, key in self._TOML_OPTIONAL_FIELDS:
            value = getattr(self, attr)
            if value is not None:
                table[key] = value
        table["installed-name"] = self.installed_name
        return table


@dataclass
class Lockfile:
    """The full lockfile state."""

    version: int = LOCKFILE_VERSION
    skills: list[LockedSkill] = field(default_factory=list)
    ralphs: list[LockedSkill] = field(default_factory=list)


def build_lockfile_path(config_path: Path) -> Path:
    """Return the lockfile path alongside the given config path."""
    return config_path.parent / LOCKFILE_FILENAME


def _parse_locked_entries(doc: TOMLDocument, key: str) -> list[LockedSkill]:
    """Parse locked entries from a TOML section."""
    entries: list[LockedSkill] = []
    for item in doc.get(key, []):
        if not isinstance(item, dict):
            continue
        entries.append(LockedSkill.from_dict(item))
    return entries


def load_lockfile(path: Path) -> Lockfile | None:
    """Load a lockfile from disk.

    Returns None if the file does not exist.
    Raises ConfigError if the file is malformed.
    """
    if not path.exists():
        return None

    try:
        content = path.read_text()
        doc = tomlkit.parse(content)
    except (TOMLKitError, OSError) as e:
        raise ConfigError(f"Invalid lockfile {path}: {e}") from e

    version = doc.get("version", LOCKFILE_VERSION)
    if version != LOCKFILE_VERSION:
        raise ConfigError(
            f"Unsupported lockfile version {version} (expected {LOCKFILE_VERSION})"
        )

    skills = _parse_locked_entries(doc, "skill")
    ralphs = _parse_locked_entries(doc, "ralph")

    return Lockfile(version=version, skills=skills, ralphs=ralphs)


def save_lockfile(lockfile: Lockfile, path: Path) -> None:
    """Write a lockfile to disk."""
    doc: TOMLDocument = tomlkit.document()
    doc.add(tomlkit.comment("This file is auto-generated by agr. Do not edit."))
    doc.add(tomlkit.nl())
    doc["version"] = lockfile.version

    def _build_aot(entries: list[LockedSkill]) -> tomlkit.items.AoT:
        aot = tomlkit.aot()
        for entry in entries:
            aot.append(entry.to_toml_table())
        return aot

    doc["skill"] = _build_aot(lockfile.skills)
    if lockfile.ralphs:
        doc["ralph"] = _build_aot(lockfile.ralphs)
    path.write_text(tomlkit.dumps(doc))


def _lockfile_list_for_dep(lockfile: Lockfile, dep: Dependency) -> list[LockedSkill]:
    """Return the appropriate lockfile list for a dependency's type."""
    if dep.type == DEPENDENCY_TYPE_RALPH:
        return lockfile.ralphs
    return lockfile.skills


def find_locked_skill(lockfile: Lockfile, dep: Dependency) -> LockedSkill | None:
    """Look up a dependency's entry in the lockfile."""
    identifier = dep.identifier
    for entry in _lockfile_list_for_dep(lockfile, dep):
        if entry.identifier == identifier:
            return entry
    return None


def is_lockfile_current(lockfile: Lockfile, dependencies: list[Dependency]) -> bool:
    """Check if the lockfile covers exactly the same deps as agr.toml.

    Returns True only if the lockfile has entries for all dependencies
    and no extra entries. Does not check whether SHAs are stale.
    """
    lockfile_skill_ids = {s.identifier for s in lockfile.skills}
    lockfile_ralph_ids = {r.identifier for r in lockfile.ralphs}
    config_skill_ids = {
        d.identifier for d in dependencies if d.type != DEPENDENCY_TYPE_RALPH
    }
    config_ralph_ids = {
        d.identifier for d in dependencies if d.type == DEPENDENCY_TYPE_RALPH
    }
    return (
        lockfile_skill_ids == config_skill_ids
        and lockfile_ralph_ids == config_ralph_ids
    )


def update_lockfile_entry(
    lockfile: Lockfile, entry: LockedSkill, *, ralph: bool = False
) -> None:
    """Add or replace an entry in the lockfile by identifier."""
    if ralph:
        lockfile.ralphs = [
            r for r in lockfile.ralphs if r.identifier != entry.identifier
        ]
        lockfile.ralphs.append(entry)
    else:
        lockfile.skills = [
            s for s in lockfile.skills if s.identifier != entry.identifier
        ]
        lockfile.skills.append(entry)


def remove_lockfile_entry(
    lockfile: Lockfile, identifier: str, *, ralph: bool = False
) -> None:
    """Remove an entry from the lockfile by identifier."""
    if ralph:
        lockfile.ralphs = [r for r in lockfile.ralphs if r.identifier != identifier]
    else:
        lockfile.skills = [s for s in lockfile.skills if s.identifier != identifier]
